let cards = [
    {
        img: "/images/shop1.webp",
        name: "Titan",
        model: "Lagan Black Dial Analog ",
        color: "Black",
        price:  2255,
    },
    {
        img: "/images/shop2.webp",
        name: "Titan",
        model: "Raga Cocktails Quartz Analog Brown ",
        color: "Brown",
        price:  49995,
    },
    {
        img: "/images/shop1.webp",
        name: "Titan",
        model: "Titan Lagan Black Dial Analog ",
        color: "Black",
        price:  2255,
    },
    {
        img: "/images/shop1.webp",
        name: "Titan",
        model: "Titan Lagan Black Dial Analog ",
        color: "Black",
        price:  2255,
    },
    {
        img: "/images/shop1.webp",
        name: "Titan",
        model: "Titan Lagan Black Dial Analog ",
        color: "Black",
        price:  2255,
    },
    {
        img: "/images/shop1.webp",
        name: "Titan",
        model: "Titan Lagan Black Dial Analog ",
        color: "Black",
        price:  2255,
    },
    {
        img: "/images/shop1.webp",
        name: "Titan",
        model: "Titan Lagan Black Dial Analog ",
        color: "Black",
        price:  2255,
    },
    {
        img: "/images/shop1.webp",
        name: "Titan",
        model: "Titan Lagan Black Dial Analog ",
        color: "Black",
        price:  2255,
    },
    {
        img: "/images/shop1.webp",
        name: "Titan",
        model: "Titan Lagan Black Dial Analog ",
        color: "Black",
        price:  2255,
    }
]